include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_redundant_argument_values: false
    avoid_dynamic_calls: false    
    

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - pubspec.yaml
  
