include: package:lint/analysis_options.yaml
# package: flutter_lints/flutter.yaml

linter:
  rules:
    avoid_deprecated_members: false
    file_names: false
    curly_braces_in_flow_control_structures: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    avoid_void_async: false
    sized_box_for_whitespace: false
    prefer_interpolation_to_compose_strings: false
    avoid_print: false
    # always_specify_types: true
    # const_initialized_with_non_constant_value: false
    # import_of_legacy_library_into_null_safe: false
    avoid_positional_boolean_parameters: false
    use_string_buffers: false
    use_build_context_synchronously: false
    depend_on_referenced_packages: false
    join_return_with_assignment: false
    unnecessary_string_escapes: false
    avoid_dynamic_calls: false
    non_constant_identifier_names: false
    no_wildcard_variable_uses: false
    constant_identifier_names: false
    unnecessary_async: false
    unused_local_variable: false
    dead_null_aware_expression: false
    


analyzer:
  errors:
    deprecated_member_use: ignore
    unused_element: ignore
    unused_field: ignore
  # enable-experiment:
      # - inline-class
  #   - records
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - maintainance/**
    - pubspec.yaml
  



# include: package:flutter_lints/flutter.yaml

# linter:
  
#   rules:
#     depend_on_referenced_packages:false
  
# analyzer:
#   exclude:
#     - "**/*.g.dart"
#   # strong-mode:
#     # implicit-casts: false
#     # implicit-dynamic: false
#   errors:
#     invalid_annotation_target: ignore
