include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_dynamic_calls: false
    no_wildcard_variable_uses: false
    

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/
    - maintainance/**
    - pubspec.yaml
  
