targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
      flutter_gen_runner: # or flutter_gen
        options:
          output: lib/generated/flutter_gen
      drift_dev:
        options:
          store_date_time_values_as_text: true
          databases:
            bull_database: lib/core/storage/sqlite_database.dart
          schema_dir: lib/core/storage/schemas/
          test_dir: test/migrations_test/
        generate_for:
          exclude:
            - "lib/core/storage/migrations/hive_to_sqlite/**"
        

