arb-dir: localization
output-dir: lib/generated/l10n
template-arb-file: app_en.arb
output-localization-file: localization.dart
untranslated-messages-file: untranslated-messages.txt
nullable-getter: false
