name: bb_mobile
description: Bull Bitcoin Mobile Wallet - Recovery Build
publish_to: "none"
version: 6.9.4+179

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.1.1
  gap: ^3.0.1
  google_fonts: ^6.3.3
  flutter_secure_storage:
    git:
      url: https://github.com/iosifpeterfi/flutter_secure_storage
      ref: 6530befdff51aa106efc38c54feb856b3831689f
      path: flutter_secure_storage
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  no_screenshot: ^0.3.1
  async: ^2.11.0
  logging_colorful: ^1.3.2
  path: ^1.9.1
  meta: ^1.17.0
  share_plus: ^12.0.1
  package_info_plus: ^9.0.0
  intl: any

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  path_provider_foundation: 2.5.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/logos/
    - assets/backgrounds/
    - assets/animations/
    - assets/misc/
