import 'package:bb_mobile/features/recipients/domain/entities/recipient.dart';
import 'package:bb_mobile/features/recipients/domain/value_objects/recipient_details.dart';
import 'package:bb_mobile/features/recipients/public/recipient_view_model.dart';

extension RecipientViewModelMapper on Recipient {
  RecipientViewModel toViewModel() => switch (details) {
    final InteracEmailCadDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      email: d.email,
      name: d.name,
    ),
    final BillPaymentCadDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      payeeName: d.payeeName,
      payeeCode: d.payeeCode,
      payeeAccountNumber: d.payeeAccountNumber,
    ),
    final BankTransferCadDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      institutionNumber: d.institutionNumber,
      transitNumber: d.transitNumber,
      accountNumber: d.accountNumber,
      name: d.name,
    ),
    final SepaEurDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      iban: d.iban,
      isCorporate: d.isCorporate,
      firstname: d.firstname,
      lastname: d.lastname,
      corporateName: d.corporateName,
    ),
    final SpeiClabeMxnDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      clabe: d.clabe,
      name: d.name,
    ),
    final SpeiSmsMxnDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      name: d.name,
    ),
    final SpeiCardMxnDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      debitcard: d.debitcard,
      name: d.name,
    ),
    final SinpeIbanUsdDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      iban: d.iban,
      ownerName: d.ownerName,
    ),
    final SinpeIbanCrcDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      iban: d.iban,
      ownerName: d.ownerName,
    ),
    final SinpeMovilCrcDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      phoneNumber: d.phoneNumber,
      ownerName: d.ownerName,
    ),
    final BankAccountArgentinaDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      name: d.name,
      bankAccount: d.claveUniform,
    ),
    final PseColombiaDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      name: d.name,
      bankAccount: d.bankAccount,
    ),
    final NequiColombiaDetails d => RecipientViewModel(
      id: recipientId,
      type: d.type,
      label: d.label,
      isOwner: d.isOwner,
      name: d.name,
      phoneNumber: d.phoneNumber,
    ),
  };
}
