// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'dart:typed_data' as i2;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    payjoinSenders,
    payjoinReceivers,
    payjoinPolicies,
    payjoinMigrations,
  ];
  late final Shape0 payjoinSenders = Shape0(
    source: i0.VersionedTable(
      entityName: 'payjoin_senders',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(uri)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 payjoinReceivers = Shape1(
    source: i0.VersionedTable(
      entityName: 'payjoin_receivers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_14,
        _column_15,
        _column_1,
        _column_16,
        _column_3,
        _column_17,
        _column_18,
        _column_7,
        _column_8,
        _column_19,
        _column_20,
        _column_21,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 payjoinPolicies = Shape2(
    source: i0.VersionedTable(
      entityName: 'payjoin_policies',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_23, _column_24, _column_25, _column_26, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 payjoinMigrations = Shape3(
    source: i0.VersionedTable(
      entityName: 'payjoin_migrations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(name)'],
      columns: [
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get uri =>
      columnsByName['uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isTestnet =>
      columnsByName['is_testnet']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sender =>
      columnsByName['sender']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get walletId =>
      columnsByName['wallet_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get originalPsbt =>
      columnsByName['original_psbt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get originalTxId =>
      columnsByName['original_tx_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get amountSat =>
      columnsByName['amount_sat']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expireAfterSec =>
      columnsByName['expire_after_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get proposalPsbt =>
      columnsByName['proposal_psbt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get txId =>
      columnsByName['tx_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isExpired =>
      columnsByName['is_expired']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isCompleted =>
      columnsByName['is_completed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isAborted =>
      columnsByName['is_aborted']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'uri',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_testnet',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_testnet IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sender',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'wallet_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'original_psbt',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'original_tx_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'amount_sat',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expire_after_sec',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'proposal_psbt',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tx_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_expired',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_expired IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_completed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_completed IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_aborted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_aborted IN (0, 1))',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get address =>
      columnsByName['address']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isTestnet =>
      columnsByName['is_testnet']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get receiver =>
      columnsByName['receiver']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get walletId =>
      columnsByName['wallet_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pjUri =>
      columnsByName['pj_uri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get maxFeeRateSatPerVb =>
      columnsByName['max_fee_rate_sat_per_vb']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expireAfterSec =>
      columnsByName['expire_after_sec']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get originalTxBytes =>
      columnsByName['original_tx_bytes']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get originalTxId =>
      columnsByName['original_tx_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get amountSat =>
      columnsByName['amount_sat']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get proposalPsbt =>
      columnsByName['proposal_psbt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get txId =>
      columnsByName['tx_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isExpired =>
      columnsByName['is_expired']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isCompleted =>
      columnsByName['is_completed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isAborted =>
      columnsByName['is_aborted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isTrade =>
      columnsByName['is_trade']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'address',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'receiver',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pj_uri',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'max_fee_rate_sat_per_vb',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_19(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'original_tx_bytes',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'original_tx_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'amount_sat',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_trade',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_trade IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enabled =>
      columnsByName['enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get tradingEnabled =>
      columnsByName['trading_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minimumAmountSat =>
      columnsByName['minimum_amount_sat']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sessionLifetimeSeconds =>
      columnsByName['session_lifetime_seconds']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (enabled IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'trading_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (trading_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'minimum_amount_sat',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'session_lifetime_seconds',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sourceSchemaVersion =>
      columnsByName['source_schema_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get senderCount =>
      columnsByName['sender_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get receiverCount =>
      columnsByName['receiver_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get verificationDigest =>
      columnsByName['verification_digest']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'source_schema_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sender_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'receiver_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'verification_digest',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
