import 'package:freezed_annotation/freezed_annotation.dart';

part 'user_address.freezed.dart';
part 'user_address.g.dart';

/// Value object representing a user's physical address.
/// Used as a field in entities like VirtualIbanRecipient.
///
/// Note: JSON serialization is kept for compatibility with UserSummary.fromJson,
/// which is auto-generated by freezed. A future refactor could remove JSON
/// from domain entities entirely.
@freezed
sealed class UserAddress with _$UserAddress {
  const factory UserAddress({
    required String street1,
    String? street2,
    required String city,
    String? province,
    required String postalCode,
    required String countryCode,
  }) = _UserAddress;

  factory UserAddress.fromJson(Map<String, dynamic> json) =>
      _$UserAddressFromJson(json);
}
