/// How a wallet's birthday was determined, which decides whether
/// [ResolveWalletBirthdayCheckpointUsecase] applies a safety margin before
/// resolving a checkpoint. See that usecase's class doc for the rationale.
enum WalletBirthdayLookupMode {
  /// A wallet just generated by this app. Its birthday is known exactly (the
  /// generation time), so it is used as-is: nothing can have been received
  /// before a wallet that did not exist yet.
  newWallet,

  /// A wallet recovered from a mnemonic/descriptor whose birthday is only an
  /// approximation (e.g. a user-entered date, or a previous install's
  /// recorded creation time). A safety margin is subtracted so the resolved
  /// checkpoint never lands after the wallet's real first-use block.
  recovery,
}

/// A verified starting point for a Bitcoin wallet's compact-block-filter
/// recovery scan: a block [blockHeight]/[blockHash] known to be at or before
/// the wallet's [requestedBirthday], together with that block's own
/// [blockTimestamp].
///
/// Deliberately **not** constructed from a guess — every instance is either
/// the network's genesis block (a protocol constant, see
/// `WalletBirthdayCheckpointRepositoryImpl`) or a block a mempool server
/// actually returned and this app validated. [blockHeight]/[blockHash] are
/// checked here (shape only); the "not later than requested" business rule
/// is enforced by the repository, which is the one place with enough
/// context (the lookup timestamp used, and how many retries remain) to
/// decide whether to retry or fail instead of silently accepting a bad
/// answer.
class WalletBirthdayCheckpoint {
  final DateTime requestedBirthday;
  final DateTime blockTimestamp;
  final int blockHeight;
  final String blockHash;

  WalletBirthdayCheckpoint({
    required this.requestedBirthday,
    required this.blockTimestamp,
    required this.blockHeight,
    required this.blockHash,
  }) {
    if (blockHeight < 0) {
      throw ArgumentError.value(
        blockHeight,
        'blockHeight',
        'Block height cannot be negative',
      );
    }
    if (!_hexHash64.hasMatch(blockHash)) {
      throw ArgumentError.value(
        blockHash,
        'blockHash',
        'Block hash must be 64 lowercase hexadecimal characters',
      );
    }
  }

  static final RegExp _hexHash64 = RegExp(r'^[0-9a-f]{64}$');

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletBirthdayCheckpoint &&
          runtimeType == other.runtimeType &&
          requestedBirthday == other.requestedBirthday &&
          blockTimestamp == other.blockTimestamp &&
          blockHeight == other.blockHeight &&
          blockHash == other.blockHash;

  @override
  int get hashCode =>
      Object.hash(requestedBirthday, blockTimestamp, blockHeight, blockHash);

  @override
  String toString() =>
      'WalletBirthdayCheckpoint(requestedBirthday: $requestedBirthday, '
      'blockTimestamp: $blockTimestamp, blockHeight: $blockHeight, '
      'blockHash: $blockHash)';
}
