targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            recoverbull_database: lib/src/database/recoverbull_database.dart
          schema_dir: lib/src/database/schemas/
          test_dir: test/migrations_test/
          store_date_time_values_as_text: true
