arb-dir: lib/l10n
template-arb-file: recoverbull_en.arb
output-localization-file: recoverbull_localizations.dart
output-class: RecoverBullLocalizations
output-dir: lib/generated/l10n
untranslated-messages-file: untranslated-messages.txt
nullable-getter: false
