import 'package:bull_ui_catalogue/catalogue_theme.dart';
import 'package:flutter/material.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;

// Generated by build_runner from every `@widgetbook.UseCase` in lib/.
// Checked into the tree (CI does not regenerate on the deploy path's behalf
// only — it does run build_runner — but the file is committed for local runs).
import 'main.directories.g.dart';

void main() {
  runApp(const BullUiCatalogue());
}

@widgetbook.App()
class BullUiCatalogue extends StatelessWidget {
  const BullUiCatalogue({super.key});

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      directories: directories,
      // WORKAROUND (widgetbook 3.24.0 on Flutter 3.44.1): the default
      // `materialAppBuilder` wraps each use-case in a nested `MaterialApp`,
      // whose Navigator trips `_history.isNotEmpty` during layout on 3.44.1.
      // The catalogue's outer app already provides MediaQuery/Directionality/
      // Overlay, and the theme is injected by `MaterialThemeAddon` (a `Theme`
      // widget), so the per-use-case shell only needs a `Material` ancestor —
      // no second `MaterialApp`/Navigator. Drop this once on widgetbook v4.
      appBuilder: (context, child) =>
          Material(type: MaterialType.transparency, child: child),
      addons: [
        // Light + dark, each carrying the BullTheme extension that components
        // read via `context.bull`. This is exactly how the app wires bull_ui.
        MaterialThemeAddon(
          themes: [
            WidgetbookTheme(
              name: 'Light',
              data: catalogueThemeData(Brightness.light),
            ),
            WidgetbookTheme(
              name: 'Dark',
              data: catalogueThemeData(Brightness.dark),
            ),
          ],
          initialTheme: WidgetbookTheme(
            name: 'Light',
            data: catalogueThemeData(Brightness.light),
          ),
        ),
        // NOTE: ViewportAddon (device frames) is intentionally omitted —
        // widgetbook 3.24.0's viewport addon trips a Navigator
        // `_history.isNotEmpty` assertion on Flutter 3.44.1 (its nested
        // Navigator asserts during layout). Re-add once widgetbook/Flutter
        // compatibility is resolved (e.g. widgetbook v4).
        TextScaleAddon(initialScale: 1.0, min: 1.0, max: 2.0, divisions: 4),
      ],
    );
  }
}
