// Regenerates integration_test/all_test.dart — the single-entrypoint aggregator
// that runs Bull.init() once, then every integration test file's
// main(isInitialized: true). On the Linux desktop device the app can be
// launched only once per `flutter test` invocation, so the whole suite must run
// through one file; this script keeps that file in sync with what's on disk so
// nobody has to hand-edit it (or silently forget to).
//
// The output is a generated build artifact: it is gitignored and regenerated on
// every `make integration-test`. Do not commit or hand-edit it.
//
// Run via: fvm dart run tools/gen_all_test.dart
import 'dart:io';

// Files matching *_test.dart that must NOT be aggregated: the generated file
// itself, plus any test with no callable main(isInitialized:) (e.g. payjoin is
// commented out and needs funded testnet wallets).
//
// get_paid_backup_roundtrip_test.dart is authored-but-CI-only: it exercises the
// Get Paid money path against the app-process DI graph, but the live startup
// timers/blocs make an app-process pump non-deterministic in the aggregated
// suite. The deterministic money-path gate is the domain-layer round-trip
// (test/features/get_paid_settings/get_paid_backup_wire_roundtrip_test.dart);
// this file is kept for a dedicated CI job with a per-test relay-only harness.
const skip = {
  'all_test.dart',
  'payjoin_test.dart',
  'get_paid_backup_roundtrip_test.dart',
  // SPEC-PP-01: same app-process non-determinism as the backup round-trip; the
  // deterministic Donation Page gates are the L0 usecase/cubit suites.
  'payment_page_lifecycle_test.dart',
};

void main() {
  final files =
      Directory('integration_test')
          .listSync()
          .whereType<File>()
          .map((f) => f.uri.pathSegments.last)
          .where((n) => n.endsWith('_test.dart') && !skip.contains(n))
          .toList()
        ..sort();

  if (files.isEmpty) {
    stderr.writeln(
      'gen_all_test: no *_test.dart files found in integration_test/',
    );
    exit(1);
  }

  final alias = {
    for (final f in files) f: f.substring(0, f.length - '_test.dart'.length),
  };

  final b = StringBuffer()
    ..writeln(
      '// GENERATED by tools/gen_all_test.dart — do not edit or commit.',
    )
    ..writeln('// Regenerated on every `make integration-test`.')
    ..writeln("import 'package:bb_mobile/main.dart';")
    ..writeln("import 'package:flutter_test/flutter_test.dart';");
  for (final f in files) {
    b.writeln("import '$f' as ${alias[f]};");
  }
  b
    ..writeln()
    ..writeln('Future<void> main() async {')
    ..writeln('  TestWidgetsFlutterBinding.ensureInitialized();')
    ..writeln('  await Bull.init();')
    ..writeln();
  for (final f in files) {
    b.writeln('  await ${alias[f]}.main(isInitialized: true);');
  }
  b.writeln('}');

  File('integration_test/all_test.dart').writeAsStringSync(b.toString());
  stdout.writeln(
    'gen_all_test: wired ${files.length} files -> integration_test/all_test.dart',
  );
}
