// Regenerates integration_test/all_test.dart — the single-entrypoint aggregator
// that runs Bull.init() once, then every integration test file's
// main(isInitialized: true). On the Linux desktop device the app can be
// launched only once per `flutter test` invocation, so the whole suite must run
// through one file; this script keeps that file in sync with what's on disk so
// nobody has to hand-edit it (or silently forget to).
//
// The output is a generated build artifact: it is gitignored and regenerated on
// every `make integration-test`. Do not commit or hand-edit it.
//
// Run via: fvm dart run tools/gen_all_test.dart
import 'dart:io';

// Files matching *_test.dart that must NOT be aggregated: only the generated
// file itself. Every real test file is wired in; a test that needs fixtures
// (e.g. payjoin's funded testnet wallets) skips itself gracefully when they
// are absent rather than being excluded here.
const skip = {'all_test.dart'};

void main() {
  final files =
      Directory('integration_test')
          .listSync()
          .whereType<File>()
          .map((f) => f.uri.pathSegments.last)
          .where((n) => n.endsWith('_test.dart') && !skip.contains(n))
          .toList()
        ..sort();

  if (files.isEmpty) {
    stderr.writeln(
      'gen_all_test: no *_test.dart files found in integration_test/',
    );
    exit(1);
  }

  final alias = {
    for (final f in files) f: f.substring(0, f.length - '_test.dart'.length),
  };

  final b = StringBuffer()
    ..writeln(
      '// GENERATED by tools/gen_all_test.dart — do not edit or commit.',
    )
    ..writeln('// Regenerated on every `make integration-test`.')
    ..writeln("import 'package:bb_mobile/main.dart';")
    ..writeln("import 'package:flutter_test/flutter_test.dart';");
  for (final f in files) {
    b.writeln("import '$f' as ${alias[f]};");
  }
  b
    ..writeln()
    ..writeln('Future<void> main() async {')
    ..writeln('  TestWidgetsFlutterBinding.ensureInitialized();')
    ..writeln('  await Bull.init();')
    ..writeln();
  for (final f in files) {
    b.writeln('  await ${alias[f]}.main(isInitialized: true);');
  }
  b.writeln('}');

  File('integration_test/all_test.dart').writeAsStringSync(b.toString());
  stdout.writeln(
    'gen_all_test: wired ${files.length} files -> integration_test/all_test.dart',
  );
}
