base_url = "https://micahkepe.com/radion"
compile_sass = true
title = "radion theme"
description = "A elegant light and dark theme for Zola"
generate_feeds = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customized by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# The theme to use for code highlighting.
# For more themes, see: https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
highlight_theme = "one-dark"

# This determines whether to insert a link for each header like the ones you can see on this site if you hover over
# a header.
# The default template can be overridden by creating an `anchor-link.html` file in the `templates` directory.
# This value can be "left", "right", "heading" or "none".
# "heading" means the full heading becomes the text of the anchor.
# See "Internal links & deep linking" in the documentation for more information.
insert_anchor_links = "heading"

[search]
index_format = "elasticlunr_json"

[extra]
author = "Micah Kepe"
github = "https://github.com/micahkepe"
radion_menu = [
    {url = "$BASE_URL/", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
radion_title = "My Example Site"

# Nicer codeblocks with copy to clipboard
codeblock = true

# Enable MathJax support
latex = true

# Enable search bar
enable_search = true

# Light/Dark Mode set
theme = "toggle" # options: {light, dark, auto, toggle}

# Whether to display favicon
favicon = true

# Giscus comment support
comments = true
giscus_repo = "micahkepe/radion"
giscus_repo_id = "R_kgDONK7lCQ"
giscus_data_category_id = "DIC_kwDONK7lCc4CnfXf"
