name: Issue Notification

on:
  issues:
    types:
      - opened

jobs:
  notify_new_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "📝 | <${{ github.event.issue.html_url }}|Issue#${{ github.event.issue.number }}> ${{ github.event.issue.title }} by *${{ github.event.issue.user.login }}*"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEAM_PORTEFEUILLE }} 