name: Notify Slack

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - develop

jobs:
  created_on_develop:
    if: github.event.pull_request.merged == false && github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "👀 | <${{ github.event.pull_request.html_url }}|PullRequest#${{ github.event.pull_request.number }}> ${{ github.event.pull_request.title }} by *${{ github.event.pull_request.user.login }}*"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEAM_PORTEFEUILLE }}

  push_to_develop:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "🔄 | <${{ github.event.repository.html_url }}/commit/${{ github.sha }}|Commit#${{ github.sha }}> ${{ github.event.head_commit.message }} by *${{ github.event.pusher.name }}*"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEAM_PORTEFEUILLE }}
